name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm
      - name: Build website
        run: |
          npm i
          npm run build

      - name: Deploy to docs.openbullet.dev
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'docs.openbullet.dev'
          project: './build'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
